# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

# Importing Dataset

In [2]:
df = tf.keras.datasets.imdb
df

<module 'keras.api._v2.keras.datasets.imdb' from 'C:\\Program Files\\Python310\\lib\\site-packages\\keras\\api\\_v2\\keras\\datasets\\imdb\\__init__.py'>

# Splitting Dataset

In [3]:
(train_features, train_labels), (test_features, test_labels) = df.load_data(num_words=10000)

In [4]:
train_features.shape

(25000,)

In [5]:
train_labels.shape

(25000,)

In [6]:
test_features.shape

(25000,)

In [7]:
test_labels.shape

(25000,)

# Checking Maximum number of words in dataset

In [8]:
max([max(sequence) for sequence in train_features])

9999

# Vectorizing train and test data

In [9]:
def vectorize_sequences(sequences, dimensions=10000):
    results = np.zeros((len(sequences), dimensions))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1
    return results

In [10]:
train_features = vectorize_sequences(train_features)
train_features

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [11]:
test_features = vectorize_sequences(test_features)
test_features

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [12]:
train_features.shape

(25000, 10000)

In [13]:
test_features.shape

(25000, 10000)

In [14]:
train_features[0]

array([0., 1., 1., ..., 0., 0., 0.])

# Creating Model

In [15]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [16]:
model.compile(optimizer='adam',
             loss=tf.keras.losses.binary_crossentropy,
             metrics=['accuracy'])

# Training Model

In [17]:
model.fit(train_features, train_labels, epochs=20)

Epoch 1/20
782/782 [==============================] - 3s 2ms/step - loss: 0.3350 - accuracy: 0.8598
Epoch 2/20
782/782 [==============================] - 2s 2ms/step - loss: 0.1911 - accuracy: 0.9291
Epoch 3/20
782/782 [==============================] - 2s 2ms/step - loss: 0.1472 - accuracy: 0.9448
Epoch 4/20
782/782 [==============================] - 2s 2ms/step - loss: 0.1160 - accuracy: 0.9569
Epoch 5/20
782/782 [==============================] - 2s 2ms/step - loss: 0.0894 - accuracy: 0.9674
Epoch 6/20
782/782 [==============================] - 1s 2ms/step - loss: 0.0651 - accuracy: 0.9765
Epoch 7/20
782/782 [==============================] - 1s 2ms/step - loss: 0.0471 - accuracy: 0.9827
Epoch 8/20
782/782 [==============================] - 1s 2ms/step - loss: 0.0294 - accuracy: 0.9908
Epoch 9/20
782/782 [==============================] - 1s 2ms/step - loss: 0.0167 - accuracy: 0.9946
Epoch 10/20
782/782 [==============================] - 1s 2ms/step - loss: 0.0262 - accuracy: 0.9911

# Checking Model Accuracy

In [18]:
test_loss, test_acc = model.evaluate(test_features, test_labels, verbose=2)
print("Test accuracy is ", test_acc)

782/782 - 1s - loss: 1.5437 - accuracy: 0.8507 - 943ms/epoch - 1ms/step
Test accuracy is  0.8507199883460999
